### ISSUE TITLE
채팅 목록 조회 기능

### ISSUE THREAD

**Issue by MinseokGo** [mut-sa-mut-si/backend#14]
# Task
- [x] 채팅방 목록을 출력한다.
- [x] #15
- [x] 채팅 상대가 누구인지 출력한다.
- [x] 카테고리별로 채팅방을 구분한다.

# Issue
- 없음
