### ISSUE TITLE
채팅방 조회 기능

### ISSUE THREAD

**Issue by MinseokGo** [mut-sa-mut-si/backend#16]
# Task
- [x] 채팅방 조회 시 해당 채팅방의 메시지 리스트를 반환한다.
- [x] 상대 유저와 자신 유저의 메시지를 구분한다.
- [x] 채팅 상대가 누구인지 알린다.

# Issue
없음
