### ISSUE TITLE
메인 페이지 구현

### ISSUE THREAD

**Issue by MinseokGo** [mut-sa-mut-si/backend#4]
# Task
- [ ] 인기 있는 레시피를 구현한다.
- [ ] 인기 있는 레시퍼를 구현한다.

# Issue
- [x] 배포 환경의 DB 연결이 안됨
